FROM johnpapa/angular-cli as builder

# COPY package.json package-lock.json ./

# ## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
# RUN npm i && mkdir /ng-app && cp -R ./node_modules ./ng-app

WORKDIR /ng-app

COPY . .

## Build the angular app in production mode and store the artifacts in dist folder
# RUN ng build --prod

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf

RUN ls -l

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY --from=builder /ng-app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
#FROM nginx
#COPY nginx.conf /etc/nginx/nginx.conf